# Generated by Django 5.0.2 on 2024-02-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorie',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='calorie',
            name='firstName',
            field=models.CharField(max_length=50),
        ),
    ]
