# Generated by Django 5.0.2 on 2024-02-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieAdmin', '0002_calorie_title_alter_calorie_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorie',
            name='calorieInput',
            field=models.IntegerField(default=0),
        ),
    ]
